### ISSUE TITLE
error insights_data_source_v3' has no attribute 'before_request' after update insights to v3.9.11

### ISSUE THREAD

**Issue by champion-alkuhlani** [frappe/insights#1133]
Faced this error 
after update insights to v3.9.11
frappe 16.14.0
the Error
`AttributeError: module 'insights.insights.doctype.insights_data_source_v3.insights_data_source_v3' has no attribute 'before_request'. Did you mean: 'after_request'?`

**Comment by nextchamp-saqib** [comment]
Can you share the full traceback? This shouldn't be happening, it was fixed a while back
